name: Test

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ./actionlint -color
        shell: bash

  lint-cruft:
    name: Check if automatic project update was successful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fail if .rej files exist as structure update was not successful
        run: test -z "$(find . -iname '*.rej')"

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry-env
      - run: poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry-env
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests and collect coverage
        run: poetry run pytest --cov=pynoonlight --cov-report=xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml

  coverage:
    name: Upload test coverage to Codecov
    runs-on: ubuntu-20.04
    needs:
      - test
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v2
      - name: Download all coverage artifacts
        uses: actions/download-artifact@v3
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
